### PR TITLE
adding skeletons for pytest

### PR DESCRIPTION
**Pull request by nicoddemus**
Adding [pytest](http://pytest.org/latest/plugins.html) skeletons for builtins.

This also fixes this issues from PyCharm tracker: PY-8005, PY-11352

### CODE REVIEW

**Comment by ionelmc** [comment]
:+1: Merge please.

**Comment by Qwlouse** [comment]
Yes, please merge! :+1:

**Comment by obestwalter** [comment]
:+1: just tried it in 4.5.4 - looks good to me.

**Comment by ionelmc** [comment]
@vlasovskikh Hey, can we get this merged? You said you'd merge it at EuroPython :grimacing:

**Pull request merged**
